### ISSUE TITLE
How to use v-money3 with <el-input /> (ElementUI)?

### ISSUE THREAD

**Issue by leeobrum** [jonathanpmartins/v-money3#74]
Hi, I'm migration my project to vue3 and pinia etc... but don't working v-money3 with my template ElementUI. My old project where I used v-money only, is working. Exemple for error: 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at B (v-money3.mjs:204:19)
    at updated (v-money3.mjs:239:95)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at invokeDirectiveHook (runtime-core.esm-bundler.js:2819:13)
    at Array.<anonymous> (runtime-core.esm-bundler.js:5380:25)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:343:32)
    at flushJobs (runtime-core.esm-bundler.js:397:9)
    at flushJobs (runtime-core.esm-bundler.js:403:13)

line of code:
<el-input v-model.lazy="oFormularioCadastro.dbAluguelEmpresa" v-money3="maskMoneyParam" />

<script setup lang="ts"> const maskMoneyParam = reactive({decimal: ',',  thousands: '.',  prefix: 'R$ ',  suffix: '',  precision: 2, masked: false }) </ script>
Main.ts
import { Money3Directive } from 'v-money3'
const app = createApp(App)

app.directive('money3', Money3Directive)

**Comment by jonathanpmartins** [comment]
What is the version of the Element project that you are using? [Element UI](https://element.eleme.io/) was made for **Vue2**. [Element Plus](https://element-plus.org/) was made for **Vue3**, same as **v-money3**. I did not test it, but **v-money3** should work fine with **Element Plus**.
For **Element UI** you should look to the original [v-money](https://github.com/vuejs-tips/v-money) project

**Comment by leeobrum** [comment]
I use element UI plus Vue 3.0 with v-money3. But it doesn't let me use the v-money3="" directive in the <el-input /> tag. I get this error from (reading 'length'). Does it only work with < input />?
In element UI Vue 2.0 I used v-money and it works 100%.

**Comment by leeobrum** [comment]
![main](https://user-images.githubusercontent.com/28123085/209220807-8762c288-464e-4a07-8a4e-a3bc0003eca5.png)
![Teste vue](https://user-images.githubusercontent.com/28123085/209220850-2a725355-7e31-4197-b140-89c963d97055.png)

**Comment by leeobrum** [comment]
![Sem título](https://user-images.githubusercontent.com/28123085/209229477-4f19d8a7-196e-4f8d-901a-f9917d88c0d6.png)


In the black square the return is only with the use of the input and it works.
In red is using the <  el-input /  > don't working

**Comment by jonathanpmartins** [comment]
Oh, now I see! You are using the directive on the ```<el-input/>``` component. This will probably not work (I did not test it).

I will suggest you to use the ```<v-money3/>``` component.

```
<money3
   v-model="dbAluguelEmpresa"
   v-bind="maskMoneyParam"
   class="el-input__inner"
/>
```

You can add the inner class to apply the styles. I think is ```el-input__inner```.

**Comment by leeobrum** [comment]
![Sem título](https://user-images.githubusercontent.com/28123085/209337910-e2be69ee-226d-40db-804a-282ec703b27d.png)

Hello, apparently it is not 100% compatible yet. But I can get around this by fixing scss and other necessary stuff. thanks for your help.
very good important this metod v-money3

**Comment by hamonCordova** [comment]
Same problem with Nuxt UI. I opened a issue on Nuxt UI repository, but the case seems the same as this issue as well.

[Nuxt UI Issue](https://github.com/nuxt/ui/issues/1704)

[Nuxt UI + v-money3 problem reproduction](https://stackblitz.com/edit/nuxt-ui-jxuirx?file=app.vue,plugins%2Fv-money3.client.ts,package.json)

I seems to the directive is binding directly with the input wrapper and did no finding the input it self.

@jonathanpmartins  could you please take a look? I'd love to see it working

**Comment by jonathanpmartins** [comment]
I just tested this with element plus. This input styling:

```html
<el-input v-model="form.model"/>
```
Is equal to this one:
```html
<div class="el-input">
  <div class="el-input__wrapper">
    <money-3-component
      v-model="form.model"
      v-bind="{}"
      class="el-input__inner"
    />
  </div>
</div>
```

I would suggest to create a custom `Money` component for your app, register it globally and use it as your money input. Example:

```vue
<script setup>
import { Money3Component } from "v-money3";

const props = defineProps({
  config: {
    type: Object,
    default: {
      decimal: ',',
      thousands: '.',
      prefix: 'R$ ',
      suffix: '',
      precision: 2,
      min: Number.MIN_SAFE_INTEGER,
      max: Number.MAX_SAFE_INTEGER,
    },
  },
});

const model = defineModel()

</script>

<template>
  <div class="el-input right">
    <div class="el-input__wrapper">
      <Money3Component
        v-model="model"
        v-bind="props.config"
        class="el-input__inner"
        style="text-align: right"
      />
    </div>
  </div>
</template>

```

**Comment by jonathanpmartins** [comment]
@hamonCordova I never ever touch any Nuxt stuff and I don't have any project to test what is going on right now. This project is primarily focused on Vue. If you spend the time and create a repository pointing the problem out, I would love to take a look at it and spend a time to perhaps solve the problem with v-money3.

**Comment by caioDelgado** [comment]
@hamonCordova, I’m encountering the same issue when using NuxtUI too.

@jonathanpmartins, I’ve created a sample repository with Nuxt, NuxtUI, and v-money3. I’d really appreciate it if you could take a look and provide any suggestions or potential fixes. Thank you!

https://github.com/caioDelgado/nuxt-v-money-sample
